### ISSUE TITLE
Makefile for making Openwrt packages

### ISSUE THREAD

**Issue by ghost** [lcdbin/ip2socks-go#1]
Great to see that it works on asus merlin, can you also provide a Makefile for Openwrt?

**Comment by lcdbin** [comment]
for golang I think it's impossible for write a makefile for every cpu,  but you can try to build this project like " GOOS=linux GOARCH=mipsle GOMIPS=softfloat CGO_ENABLED=0 go build . "

I would add my build args for asus merlin ac86u into Makefile
